title: Homepage
description: 主动的人掌握主动权，勇敢的人先享受世界.
author: 张琳
avatar: /logo.png
email: bit.zhanglin@bit.edu.cn
location: China, Beijing
subscribe: False

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: logo.png
social:
  name: Lin Zhang
  links:
    # - https://github.com/Eric-ZhangL
    # - https://www.facebook.com/ngzhio
    - https://github.com/Eric-ZhangL
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
